kind: ConfigMap
apiVersion: v1
metadata:
  name: daprbackend-cm
  namespace: daprdemodotnet
  labels:
    app: daprdemodotnet
    service: daprbackend
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  OrchestratorType: K8S
  PORT: "80"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprbackend
  namespace: daprdemodotnet
  labels:
    app: daprdemodotnet
    service: daprbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprdemodotnet
      service: daprbackend
  template:
    metadata:
      labels:
        app: daprdemodotnet
        service: daprbackend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprbackend"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing-config"
    spec:
      containers:
        - name: daprbackend-api
          image: daprbackend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: daprbackend-cm

---

apiVersion: v1
kind: Service
metadata:
  name: daprbackend-api
  namespace: daprdemodotnet
  labels:
    app: daprdemodotnet
    service: daprbackend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    service: daprbackend