apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: daprdemodotnet
  annotations:
    meta.helm.sh/release-name: redis
    meta.helm.sh/release-namespace: default
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: redis-12.10.0
    heritage: Helm
    release: redis
type: Opaque
data:
  redis-password: QVJKRmRRR3dzSQ==