version: "3.4"

services:
<<<<<<< HEAD

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim
=======
  redis:
    image: redis:latest
    ports:
      - "5379:6379"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "5411:9411"
>>>>>>> 2826c1fcc726930dbaa4c8ba32438219f82c71b8

  daprfrontend:
    image: ${DOCKER_REGISTRY-}daprfrontend
    build:
      context: .
<<<<<<< HEAD
      dockerfile: DaprFrontEnd/Dockerfile   
        

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprfrontend     
    network_mode: "service:daprfrontend" 
=======
      dockerfile: DaprFrontEnd/Dockerfile
    ports:
      - "51001:50001"
      - "9081:80" 

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprfrontend",
        "-app-port",
        "80",
        "-components-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
      ]
    depends_on:
      - daprfrontend
    network_mode: "service:daprfrontend"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
>>>>>>> 2826c1fcc726930dbaa4c8ba32438219f82c71b8

  daprbackend:
    image: ${DOCKER_REGISTRY-}daprbackend
    build:
      context: .
      dockerfile: DaprBackEnd/Dockerfile
<<<<<<< HEAD

  daprbackend-dapr:
    image: "daprio/daprd:latest"
=======
    ports:
      - "55000:50001"
      - "9080:8080"

  daprbackend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprbackend",
        "-app-port",
        "80",
        "-components-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
      ]
>>>>>>> 2826c1fcc726930dbaa4c8ba32438219f82c71b8
    depends_on:
      - daprbackend     
    network_mode: "service:daprbackend"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprbackend-dashboard:
<<<<<<< HEAD
    image: "daprio/dashboard:latest"   
  
  dapr-placement:
    image: "daprio/dapr:latest"     

=======
    image: "daprio/dashboard:latest"
    command:
      [
        "./daprd",
        "dashboard"
      ]
    depends_on:
      - daprfrontend
    network_mode: "service:daprbackend"
    volumes:
      - "./dapr/components/:/root/.dapr/components"
      - "./dapr/configuration/:/root/.dapr/configuration"
>>>>>>> 2826c1fcc726930dbaa4c8ba32438219f82c71b8
