version: '3.4'

services:
  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"

  daprfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "9081:80"        
      - "3501:3500"
      - "52001:50001" 

  daprfrontend-dapr:
    command: [ "./daprd", "-app-id", "daprfrontend", "-app-port", "80","-components-path", "/components","-config", "/configuration/config.yaml"]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
   

  daprbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9082:80"        
      - "3502:3500"  
      - "52000:50001" 

  daprbackend-dapr: 
    command: [ "./daprd","-app-id", "daprbackend","-app-port", "80","-components-path", "/components","-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprbackend-dashboard: 
    command: [ "./daprd", "dashboard"]
    volumes:
      - "./dapr/components/:/root/.dapr/components"
      - "./dapr/configuration/:/root/.dapr/"
    ports:
      - "9080:8080"
      - "53000:50001" 

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    volumes:
      - "./dapr/components/:/root/.dapr/components"
      - "./dapr/configuration/:/root/.dapr/"
    ports:
      - "50000:50000" 
   
