version: '3.4'

services:

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  daprfrontend:
    image: ${DOCKER_REGISTRY-}daprfrontend
    build:
      context: .
      dockerfile: DaprFrontEnd/Dockerfile   
        

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprfrontend     
    network_mode: "service:daprfrontend" 

  daprbackend:
    image: ${DOCKER_REGISTRY-}daprbackend
    build:
      context: .
      dockerfile: DaprBackEnd/Dockerfile

  daprbackend-dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprbackend     
    network_mode: "service:daprbackend"
    
  daprbackend-dashboard:
    image: "daprio/dashboard:latest"   
  
  dapr-placement:
    image: "daprio/dapr:latest"     

