apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
<<<<<<< HEAD
  namespace: default
=======
>>>>>>> 2826c1fcc726930dbaa4c8ba32438219f82c71b8
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
